{
 "title": "VM-exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU 占用",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"demo\"}[1m]) *100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "物理内存占用",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存分配趋势",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go routine",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "堆内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "线程数量",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "go_threads{job=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "垃圾回收耗时统计",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"demo\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}